project:
  type: website
  output-dir: docs
  render: 
    - "*qmd"


website:
  title: "Elizabeth Porter"
  #google-analytics: 
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: files/Elizabeth_Porter_CV.pdf
        text: CV
        target: "_blank"
    
    right:
      - icon: github
        href: http://github.com/elizabeth-porter
        target: "_blank"


format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

